### ISSUE TITLE
Random error on the slicer

### ISSUE THREAD

**Issue by filalia** [Microsoft/PowerBI-visuals-ChicletSlicer#24]
Hi, 
Since a week i have a random error on my report wich worked fine before : 
![image](https://cloud.githubusercontent.com/assets/28589184/25887788/c94f0f1a-3563-11e7-8fbf-fd99722f8de3.png)

regards

**Comment by vtkalek** [comment]
Hi, Filalia. 

Can you, please, provide more information about your issue? We need your report with data or description about how to reproduce the issue.

**Comment by uve** [comment]
Hello @filalia,
 This issue has been fixed and it should work now.
 Please check it again and let me know if this error still occurs.
