### ISSUE TITLE
Chiclet Slicer v1.4.5: Property "Show Disabled" not working?

### ISSUE THREAD

**Issue by StolzHerz** [microsoft/PowerBI-visuals-ChicletSlicer#41]
Hi 

I use the chicletSlicer.1.4.5.0.pbiviz in Power BI Desktop (optimized for Power BI Report Server June 2017), and connect to a SSAS Tabular model.

The slicer has a property "Show Disabled" with options "Inplace", "Bottom", "Hide"
**Can it be that this propery has no effect?** Always all Dim-items are available in the slicer, independet whether they have corresponding Facts-items or not.

When i connect the same SSAS Tabular model with Excel 2013, and add a slicer there, unused Dim-items are disabled.

Greetings, Stolzi

**Comment by uve** [comment]
Hello @StolzHerz, thank you for your feedback.
Yes, you're right, latest version of ChicletSlicer doesn't support highlighting anymore.
So "Show Disabled" options doesn't work, it will be removed in the next version of the visual.

**Comment by StolzHerz** [comment]
Hi uve

Instead of removing, better re-implement the functionality! Still poor old excel can do that. I have dimensions with 100 items an more, but I only want to show the relevant (speak: used) dim items related to the current filter context. It makes totally no sense to show 100 items in the slicer when only 5 have related fact rows... thats a frustrating user experience: Clicking on slicer buttons and nothing happens...

Many thanks, StolzHerz

**Comment by SebastienPaquet** [comment]
Hi uve, that was a great feature
it is still available as of 2020-06-29 but still not working
could you implement it ?

I studied programming could I help ?
Thank you, have a nice day !

**Comment by helen508light** [comment]
Highlights are supported by chicklet slicer now

**Comment by helen508light** [comment]
Now it works. If you have any specific issues on your datasets, please send this datasets or screenshots
