### ISSUE TITLE
Not working with Bookmarks

### ISSUE THREAD

**Issue by PurdyTDB** [Microsoft/PowerBI-visuals-ChicletSlicer#48]
When using bookmarks, the status of buttons on the visuals do not change, even when values on report does, leading to misreading info.

**Comment by uve** [comment]
@PurdyTDB, bookmarks is experimental feature and some visuals don't support it yet. We plan to release new version of ChicletSlicer with bookmarks support soon.

**Comment by NielsSkytte** [comment]
Any news on an updated version? We see the same behavior, e.g. when we use a bookmark to clear all slicers the chiclet slicer buttons does not revert even though the filter is correctly cleared from the data.

**Comment by ignatvilesov** [comment]
Chiclet Slicer [v1.4.8](https://github.com/Microsoft/PowerBI-visuals-ChicletSlicer/releases/tag/1.4.8) supports Bookmarks now.
This version is going to hit production next Tuesday :rocket:
