### ISSUE TITLE
Bookmarking/link possibility missing

### ISSUE THREAD

**Issue by fjellfisk** [Microsoft/PowerBI-visuals-ChicletSlicer#49]
It would be nice to have a link functionality to another dashboard or bookmark when selecting items in slicer.

best regards.

Terje

**Comment by uve** [comment]
Hello @fjellfisk, we plan to release new version of ChicletSlicer in March, it will support [bookmarks](https://docs.microsoft.com/en-us/power-bi/desktop-bookmarks) functionality.
