### ISSUE TITLE
Chiclet filter no longer working on Published Power BI

### ISSUE THREAD

**Issue by rajchauhan12** [microsoft/PowerBI-visuals-ChicletSlicer#59]
The filtering of Chiclet works when using the Power BI Desktop, but once I publish it none of the Chiclet Slicer filter based on a Matrix Table selection.  I have already deleted the dataset/report and republished the PBIX files and this did not fix the issues.  This issues just started recently (within the past 3-4 days).  Before that everything was working correctly.  Does not matter which browser is used (Chrome, IE11, Edge).  Other user also experience the same issue viewing my dashboard.

**Comment by Dmitriyf1** [comment]
Hi everyone, I and my team have the same issue on Published version. As of desktop everything working fine. But on iPad app, web version - not. Could you please fix it ? Thank you for your efforts.

**Comment by helen508light** [comment]
has already been resolved
